[functions]
  external_node_modules = ["express", "csurf", "cookie-parser", "serverless-http", "pug", "path"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/index/:splat"