[functions]
  external_node_modules = ["express", "csurf", "cookie-parser", "serverless-http", "ejs", "resend", "dotenv", "multer"]
  node_bundler = "esbuild"
  included_files = ["page_views/*", "email_templates/*"]
# Necessary because express.static('public') wasn't working as intended when mixing with Netlify
[[redirects]]
  force = true
  from = "/public/*"
  status = 200
  to = "/public/:splat"
[[redirects]]
  force = true
  from = "/images/carousel/:url"
  status = 200
  to = "/.netlify/images/?url=/public/images/carousel/:url&fm=webp"
[[redirects]]
  force = true
  from = "/images/:url/:width/:height"
  status = 200
  to = "/.netlify/images/?url=/public/images/:url&w=:width&h=:height&fm=webp"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/index/:splat"